function ct_x = cost_qN(in1)
%cost_qN
%    CT_X = cost_qN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Jul-2025 18:07:21

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
ct_x = [x1;x2;x3.*2.0;x4.*2.0;x5.*2.0;x6./5.0;x7./5.0;x8.*2.0e+2-6.0e+2;x9.*2.0e+2;x10.*2.0e+2+8.0e+2];
end
