function cs_uu = cost_Rk2(t,in2,in3)
%cost_Rk2
%    CS_UU = cost_Rk2(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Jul-2025 18:07:22

cs_uu = reshape([2.0e-6,0.0,0.0,0.0,2.0e-6,0.0,0.0,0.0,2.0e-6],[3,3]);
end
