function cs_u = cost_rk(t,in2,in3)
%COST_RK
%    CS_U = COST_RK(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Jul-2025 18:07:22

f1 = in3(1,:);
f2 = in3(2,:);
f3 = in3(3,:);
cs_u = [f1./5.0e+5;f2./5.0e+5;f3./5.0e+5+7.84532e-5];
end
