function cost_term = cost_gN(in1)
%cost_gN
%    COST_TERM = cost_gN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Jul-2025 18:07:21

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
cost_term = (x8.*1.0e+2-3.0e+2).*(x8-3.0)+(x10.*1.0e+2+4.0e+2).*(x10+4.0)+x1.^2./2.0+x2.^2./2.0+x3.^2+x4.^2+x5.^2+x6.^2./1.0e+1+x7.^2./1.0e+1+x9.^2.*1.0e+2;
end
