function out1 = discretize_B_lin(in1,T_k)
%discretize_B_lin
%    OUT1 = discretize_B_lin(IN1,T_k)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Jul-2025 18:07:21

Blin1_1 = in1(1);
Blin1_2 = in1(11);
Blin1_3 = in1(21);
Blin2_1 = in1(2);
Blin2_2 = in1(12);
Blin2_3 = in1(22);
Blin3_1 = in1(3);
Blin3_2 = in1(13);
Blin3_3 = in1(23);
Blin4_1 = in1(4);
Blin4_2 = in1(14);
Blin4_3 = in1(24);
Blin5_1 = in1(5);
Blin5_2 = in1(15);
Blin5_3 = in1(25);
Blin6_1 = in1(6);
Blin6_2 = in1(16);
Blin6_3 = in1(26);
Blin7_1 = in1(7);
Blin7_2 = in1(17);
Blin7_3 = in1(27);
Blin8_1 = in1(8);
Blin8_2 = in1(18);
Blin8_3 = in1(28);
Blin9_1 = in1(9);
Blin9_2 = in1(19);
Blin9_3 = in1(29);
Blin10_1 = in1(10);
Blin10_2 = in1(20);
Blin10_3 = in1(30);
t2 = T_k.^2;
t3 = T_k.^3;
t4 = t2.^2;
mt1 = [(Blin1_1.*t2)./2.0+(Blin1_1.*t3)./6.0+(Blin1_1.*t4)./2.4e+1+Blin1_1.*T_k,(Blin2_1.*t2)./2.0+(Blin2_1.*t3)./6.0+(Blin2_1.*t4)./2.4e+1+Blin2_1.*T_k,(Blin3_1.*t2)./2.0+(Blin3_1.*t3)./6.0+(Blin3_1.*t4)./2.4e+1+Blin3_1.*T_k,(Blin4_1.*t2)./2.0+(Blin4_1.*t3)./6.0+(Blin4_1.*t4)./2.4e+1+Blin4_1.*T_k,(Blin5_1.*t2)./2.0+(Blin5_1.*t3)./6.0+(Blin5_1.*t4)./2.4e+1+Blin5_1.*T_k,(Blin6_1.*t2)./2.0+(Blin6_1.*t3)./6.0+(Blin6_1.*t4)./2.4e+1+Blin6_1.*T_k,(Blin7_1.*t2)./2.0+(Blin7_1.*t3)./6.0+(Blin7_1.*t4)./2.4e+1+Blin7_1.*T_k,(Blin8_1.*t2)./2.0+(Blin8_1.*t3)./6.0+(Blin8_1.*t4)./2.4e+1+Blin8_1.*T_k];
mt2 = [(Blin9_1.*t2)./2.0+(Blin9_1.*t3)./6.0+(Blin9_1.*t4)./2.4e+1+Blin9_1.*T_k,(Blin10_1.*t2)./2.0+(Blin10_1.*t3)./6.0+(Blin10_1.*t4)./2.4e+1+Blin10_1.*T_k,(Blin1_2.*t2)./2.0+(Blin1_2.*t3)./6.0+(Blin1_2.*t4)./2.4e+1+Blin1_2.*T_k,(Blin2_2.*t2)./2.0+(Blin2_2.*t3)./6.0+(Blin2_2.*t4)./2.4e+1+Blin2_2.*T_k,(Blin3_2.*t2)./2.0+(Blin3_2.*t3)./6.0+(Blin3_2.*t4)./2.4e+1+Blin3_2.*T_k,(Blin4_2.*t2)./2.0+(Blin4_2.*t3)./6.0+(Blin4_2.*t4)./2.4e+1+Blin4_2.*T_k,(Blin5_2.*t2)./2.0+(Blin5_2.*t3)./6.0+(Blin5_2.*t4)./2.4e+1+Blin5_2.*T_k,(Blin6_2.*t2)./2.0+(Blin6_2.*t3)./6.0+(Blin6_2.*t4)./2.4e+1+Blin6_2.*T_k];
mt3 = [(Blin7_2.*t2)./2.0+(Blin7_2.*t3)./6.0+(Blin7_2.*t4)./2.4e+1+Blin7_2.*T_k,(Blin8_2.*t2)./2.0+(Blin8_2.*t3)./6.0+(Blin8_2.*t4)./2.4e+1+Blin8_2.*T_k,(Blin9_2.*t2)./2.0+(Blin9_2.*t3)./6.0+(Blin9_2.*t4)./2.4e+1+Blin9_2.*T_k,(Blin10_2.*t2)./2.0+(Blin10_2.*t3)./6.0+(Blin10_2.*t4)./2.4e+1+Blin10_2.*T_k,(Blin1_3.*t2)./2.0+(Blin1_3.*t3)./6.0+(Blin1_3.*t4)./2.4e+1+Blin1_3.*T_k,(Blin2_3.*t2)./2.0+(Blin2_3.*t3)./6.0+(Blin2_3.*t4)./2.4e+1+Blin2_3.*T_k,(Blin3_3.*t2)./2.0+(Blin3_3.*t3)./6.0+(Blin3_3.*t4)./2.4e+1+Blin3_3.*T_k,(Blin4_3.*t2)./2.0+(Blin4_3.*t3)./6.0+(Blin4_3.*t4)./2.4e+1+Blin4_3.*T_k];
mt4 = [(Blin5_3.*t2)./2.0+(Blin5_3.*t3)./6.0+(Blin5_3.*t4)./2.4e+1+Blin5_3.*T_k,(Blin6_3.*t2)./2.0+(Blin6_3.*t3)./6.0+(Blin6_3.*t4)./2.4e+1+Blin6_3.*T_k,(Blin7_3.*t2)./2.0+(Blin7_3.*t3)./6.0+(Blin7_3.*t4)./2.4e+1+Blin7_3.*T_k,(Blin8_3.*t2)./2.0+(Blin8_3.*t3)./6.0+(Blin8_3.*t4)./2.4e+1+Blin8_3.*T_k,(Blin9_3.*t2)./2.0+(Blin9_3.*t3)./6.0+(Blin9_3.*t4)./2.4e+1+Blin9_3.*T_k,(Blin10_3.*t2)./2.0+(Blin10_3.*t3)./6.0+(Blin10_3.*t4)./2.4e+1+Blin10_3.*T_k];
out1 = reshape([mt1,mt2,mt3,mt4],10,3);
end
